- stage: Deploy
  displayName: Deploy to AKS

  dependsOn: Build

  jobs:

  - job: Deploy

    displayName: Deploy Application

    steps:

    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy to AKS

      inputs:

        action: deploy

        kubernetesServiceConnection: aks-sc

        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml

        containers: |
          timetrackeracr2026.azurecr.io/time-tracker:$(Build.BuildId)
