trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: time-tracker
  dockerfilePath: Dockerfile
  tag: $(Build.BuildId)

stages:

- stage: Build

  jobs:

  - job: Build

    steps:

    - task: Docker@2

      displayName: Build Image

      inputs:

        command: build

        containerRegistry: docker-acr-sc

        repository: $(imageRepository)

        dockerfile: $(dockerfilePath)

        tags: |
          $(tag)

    - task: Docker@2

      displayName: Push Image

      inputs:

        command: push

        containerRegistry: docker-acr-sc

        repository: $(imageRepository)

        tags: |
          $(tag)
