trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: time-tracker
  dockerfilePath: Dockerfile
  tag: $(Build.BuildId)

stages:

#========================================
# Build & Push Docker Image
#========================================

- stage: Build
  displayName: Build and Push Docker Image

  jobs:

  - job: Build

    steps:

    - checkout: self

    - task: Docker@2
      displayName: Build Docker Image

      inputs:
        command: build
        containerRegistry: docker-acr-sc
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push Docker Image

      inputs:
        command: push
        containerRegistry: docker-acr-sc
        repository: $(imageRepository)
        tags: |
          $(tag)

#========================================
# Deploy to AKS
#========================================

- stage: Deploy
  displayName: Deploy to AKS

  dependsOn: Build

  jobs:

  - deployment: Deploy

    displayName: Deploy Application

    environment: aks

    strategy:

      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: KubernetesManifest@1

            displayName: Deploy to AKS

            inputs:

              action: deploy

              kubernetesServiceConnection: aks-sc

              manifests: |
                k8s/deployment.yaml
                k8s/service.yaml

              containers: |
                timetrackeracr2026.azurecr.io/time-tracker:$(Build.BuildId)
